CREATE TABLE BAZKIDE(
  Kodea VARCHAR(15) NOT NULL,
  Pasahitza VARCHAR(15) NOT NULL,
  Izena VARCHAR(15),
  Abizena VARCHAR(15),
  Helbidea VARCHAR(15),
  Kreditua SMALLINT DEFAULT 0,
  Egoera VARCHAR(15) DEFAULT 'alta',
  Noiztik DATETIME,
  PRIMARY KEY(Kodea)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PELIKULA(
  Kodea VARCHAR(15) NOT NULL,
  Izena VARCHAR(15),
  Prezioa TINYINT,
  Egoera VARCHAR(15) DEFAULT 'libre',
  Sartze_data DATE,
  PRIMARY KEY(Kodea)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ALOKAIRUAK{
  Bazkide_kodea VARCHAR(15) NOT NULL,
  Pelikula_kodea VARCHAR(15) NOT NULL,
  Hartze_data DATE,
  Itzultze_data DATE,
  PRIMARY KEY(Bazkide_kodea, Pelikula_kodea, Hartze_data, Itzultze_data)
  FOREIGN KEY(Bazkide_kodea) REFERENCES BAZKIDE(Kodea) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(Pelikula_kodea) REFERENCES PELIKULA(Kodea) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
