CREATE TABLE BAZKIDE(
  Kodea VARCHAR(15) NOT NULL,
  Pasahitza VARCHAR(15) NOT NULL,
  Izena VARCHAR(64),
  Abizena VARCHAR(64),
  Helbidea VARCHAR(15),
  Kreditua SMALLINT DEFAULT 0,
  Egoera VARCHAR(15) DEFAULT 'alta',
  Noiztik DATETIME,
  PRIMARY KEY(Kodea)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PELIKULA(
  Kodea VARCHAR(15) NOT NULL,
  Izena VARCHAR(64),
  Prezioa TINYINT(1),
  Egoera VARCHAR(15) DEFAULT 'libre',
  Sartze_data DATETIME,
  PRIMARY KEY(Kodea)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE ALOKAIRUAK(
  Bazkide_kodea VARCHAR(15) NOT NULL,
  Pelikula_kodea VARCHAR(15) NOT NULL,
  Hartze_data DATETIME,
  Itzultze_data DATETIME,
  PRIMARY KEY(Bazkide_kodea, Pelikula_kodea, Hartze_data),
  FOREIGN KEY(Bazkide_kodea) REFERENCES BAZKIDE(Kodea) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(Pelikula_kodea) REFERENCES PELIKULA(Kodea) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
